version: '3.9'

services:
  local:
    build:
      context: .
      dockerfile: Dockerfile
      target: local
    container_name: local
    volumes:
      - ./src:/usr/fast/app/src
      - ./nodemon.json:/usr/fast/app/nodemon.json
    expose:
      - '3001'
    ports:
      - '3001:3001'
    command: npm run dev
    networks:
      - local

networks:
  local: